/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was normally generated by TanStack Router, but manually restored to fix build errors.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes
import { Route as rootRoute } from './routes/__root'
import { Route as MarketImport } from './routes/market'
import { Route as IndexImport } from './routes/index'
import { Route as AssetsImport } from './routes/assets'
import { Route as AssetsAssetIdImport } from './routes/assets.$assetId'

// Create/Update Routes
const MarketRoute = MarketImport.update({
  path: '/market',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AssetsRoute = AssetsImport.update({
  path: '/assets',
  getParentRoute: () => rootRoute,
} as any)

const AssetsAssetIdRoute = AssetsAssetIdImport.update({
  path: '/$assetId',
  getParentRoute: () => AssetsRoute,
} as any)

// Populate the FileRoutes variable
export interface FileRoutes {
  '/': {
    id: '/'
    path: '/'
    fullPath: '/'
    preLoaderRoute: typeof IndexImport
    parentRoute: typeof rootRoute
  }
  '/market': {
    id: '/market'
    path: '/market'
    fullPath: '/market'
    preLoaderRoute: typeof MarketImport
    parentRoute: typeof rootRoute
  }
  '/assets': {
    id: '/assets'
    path: '/assets'
    fullPath: '/assets'
    preLoaderRoute: typeof AssetsImport
    parentRoute: typeof rootRoute
  }
  '/assets/$assetId': {
    id: '/assets/$assetId'
    path: '/$assetId'
    fullPath: '/assets/$assetId'
    preLoaderRoute: typeof AssetsAssetIdImport
    parentRoute: typeof AssetsImport
  }
}

// Export the Route Tree
export const routeTree = rootRoute.addChildren([
  IndexRoute,
  MarketRoute,
  AssetsRoute.addChildren([AssetsAssetIdRoute]),
])